version = 0.1

[default.deploy.parameters]
stack_name = "aig"
resolve_s3 = true
s3_prefix = "aig"
region = "eu-west-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "eu-west-1"
